recruitment-process-system-2012/Source Code/RecruitmentProcessSystem/src/java/rps/managedBean/ApplicantInfoBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rps.managedBean;

import java.io.Serializable;
import java.util.List;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import rps.business.ApplicantService;
import rps.business.InterviewService;
import rps.business.VacancyService;
import rps.entities.Applicant;
import rps.entities.Interview;

/**
 *
 * @author user
 */
@ManagedBean
@ViewScoped
public class ApplicantInfoBean implements Serializable{

    private VacancyService vacancyService;
    private ApplicantService applicantService;
    private InterviewService interviewService;

    /** Creates a new instance of ApplicantInfoBean */
    public ApplicantInfoBean() {
        vacancyService = new VacancyService();
        applicantService = new ApplicantService();
        interviewService = new InterviewService();
    }
    // <editor-fold defaultstate="collapsed" desc="applicant-info.xhtml">
    // <editor-fold defaultstate="collapsed" desc="APPLICANT INFORMATION">
    private Applicant applicant;

    public Applicant getApplicant() {
        try {
            Map<String, String> params =
                    FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
            String id = params.get("id");
            if (id != null && !id.equals("")) {
                applicant = applicantService.getApplicant(id);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return applicant;
    }
    private List<Interview> interviews;

    public List<Interview> getInterviews() {
        if (getApplicant() != null) {
            interviews = interviewService.getInterviews(applicant);
        }
        return interviews;
    }

    public void viewSchedule() {
        try {
            Map<String, Object> params =
                    FacesContext.getCurrentInstance().getViewRoot().getViewMap();
            ScheduleBean bean = (ScheduleBean) params.get("scheduleBean");
            if (bean != null) {
                Map<String, String> params2 =
                        FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
                String id = params2.get("iid");
                bean.setInterview(interviewService.getInterview(id));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    // </editor-fold>
    // </editor-fold>
}

recruitment-process-system-2012/Source Code/RecruitmentProcessSystem/src/java/rps/managedBean/VacancyInfoBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rps.managedBean;

import java.io.Serializable;
import java.util.List;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import rps.business.ApplicantService;
import rps.business.InterviewService;
import rps.business.VacancyService;
import rps.entities.Interview;
import rps.entities.Vacancy;

/**
 *
 * @author user
 */
@ManagedBean
@ViewScoped
public class VacancyInfoBean implements Serializable {

    private VacancyService vacancyService;
    private ApplicantService applicantService;
    private InterviewService interviewService;

    /** Creates a new instance of VacancyInfoBean */
    public VacancyInfoBean() {
        vacancyService = new VacancyService();
        applicantService = new ApplicantService();
        interviewService = new InterviewService();
    }
    // <editor-fold defaultstate="collapsed" desc="vacancy-info.xhtml">
    // <editor-fold defaultstate="collapsed" desc="VACANCY INFORMATION">
    private Vacancy vacancy;

    public Vacancy getVacancy() {
        try {
            Map<String, String> params =
                    FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
            String id = params.get("id");
            if (id != null && !id.equals("")) {
                vacancy = vacancyService.getDetailVacancy(id);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return vacancy;
    }
    private List<Interview> interviews;

    public List<Interview> getInterviews() {
        if (getVacancy() != null) {
            interviews = interviewService.getInterviews(vacancy);
        }
        return interviews;
    }

    public void viewSchedule() {
        try {
            Map<String, Object> params =
                    FacesContext.getCurrentInstance().getViewRoot().getViewMap();
            ScheduleBean bean = (ScheduleBean) params.get("scheduleBean");
            if (bean != null) {
                Map<String, String> params2 =
                        FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
                String id = params2.get("iid");
                bean.setInterview(interviewService.getInterview(id));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    // </editor-fold>
    // </editor-fold>
}

recruitment-process-system-2012/Source Code/RecruitmentProcessSystem/src/java/rps/managedBean/VacancyMB.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rps.managedBean;

import java.io.Serializable;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.component.UIComponent;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;
import javax.servlet.http.HttpServletRequest;
import rps.business.DepartmentService;
import rps.business.VacancyService;
import rps.entities.Department;
import rps.entities.Vacancy;

/**
 *
 * @author user
 */
@ManagedBean
@RequestScoped
public class VacancyMB implements Serializable {

    private Vacancy vacancy;
    private String vacancyID;
    private Department department;
    private List<Vacancy> lstVacancy;
    private VacancyService vacancyService;
    private DepartmentService departmentService;

    /** Creates a new instance of VacancyMB */
    public VacancyMB() {
        vacancyService = new VacancyService();
        departmentService = new DepartmentService();
    }

    public String search() {
        vacancyService = new VacancyService();
        lstVacancy = vacancyService.getListVacancyByID(vacancyID);
        return null;
    }

    public List<Vacancy> getLstVacancy() {
        return lstVacancy;
    }

    public void setLstVacancy(List<Vacancy> lstVacancy) {
        this.lstVacancy = lstVacancy;
    }

    public VacancyService getVacancyService() {
        return vacancyService;
    }

    public void setVacancyService(VacancyService vacancyService) {
        this.vacancyService = vacancyService;
    }

    public Department getDepartment() {
        if (department == null) {
            department = new Department();
        }
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public Vacancy getVacancy() {
        if (vacancy == null) {
            HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
            String paramID = request.getParameter("id");
            if (paramID == null || paramID.equals("")) {
                vacancy = new Vacancy();

            } else {
                try {
                    vacancy = vacancyService.getDetailVacancy(paramID);
                } catch (Exception ex) {
                    FacesMessage message = new FacesMessage(
                            FacesMessage.SEVERITY_WARN,
                            "Vacancy not found!",
                            "Vacancy not found!");
                    FacesContext.getCurrentInstance().addMessage(null, message);
                    vacancy = new Vacancy();
                }
            }
        }
        return vacancy;
    }

    public void setVacancy(Vacancy vacancy) {
        this.vacancy = vacancy;
    }
    private List<Vacancy> list;

    public List<Vacancy> getList() {
        return list;
    }

    public void setList(List<Vacancy> list) {
        this.list = list;
    }

    public String insertVacancy() {
        if (!validateInput()) {
            return null;
        }
        vacancyService = new VacancyService();
        vacancyService.beginTransaction();
        if (department == null) {
            department = new Department();
        }

        department = departmentService.getDeparmentById(id);
        vacancyService.insertVacancy(vacancy.getTitle(), department, vacancy.getNumberRequirement(),
                vacancy.getPosition(), vacancy.getWorkingPlace(), vacancy.getWorkType(),
                vacancy.getMinimumSalary(), vacancy.getMaximumSalary(), vacancy.getDescription(),
                vacancy.getSkillRequirement(), vacancy.getEntitlement(), vacancy.getMinimumAge(), vacancy.getMaximumAge(),
                vacancy.getGender(), vacancy.getDegree(), vacancy.getYearOfExperience(), vacancy.getProbationaryPeriod(), vacancy.getDeadline());
        vacancyService.commitTransaction();
        FacesMessage message = new FacesMessage(
                FacesMessage.SEVERITY_INFO,
                "INFORMATION",
                "Create a new vacancy successful");
        FacesContext.getCurrentInstance().addMessage(null, message);
        vacancy = null;
        vacancyID = "";
        id = "";
        return null;
    }

    public List<Department> getDepartments() {
        return departmentService.getDepartments();
    }
    private String id;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void validateNumberRequirement(FacesContext context, UIComponent component, Object obj) throws ValidatorException {
        UIInput uIInput = (UIInput) component;
        if (uIInput.isRequired() && uIInput.isValid()) {
            int numberValue = (Integer) obj;
            if (numberValue <= 0) {
                FacesMessage message = new FacesMessage(
                        FacesMessage.SEVERITY_WARN,
                        "Number Requirement is invalid",
                        "Number Requirement is invalid");
                throw new ValidatorException(message);
            }
        }
    }

    public void validateYearOfExperience(FacesContext context, UIComponent component, Object obj) throws ValidatorException {
        UIInput uIInput = (UIInput) component;
        if (uIInput.isValid()) {
            int number = (Integer) obj;
            if (number < 0) {
                FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_WARN, "Number Requirement is validate", "Number Requirement must a integer number");
                throw new ValidatorException(message);
            }
        }
    }

    public void validateMinSalary(FacesContext context, UIComponent component, Object obj) throws ValidatorException {
        UIInput iInput = (UIInput) component;
        if (iInput.isValid()) {
            Double number = (Double) obj;
            if (number < 0) {
                FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_WARN, "Number is invalid", "Number is invalid");
                throw new ValidatorException(message);
            }
        }
    }

    public void validateMaxSalary(FacesContext context, UIComponent component, Object obj) throws ValidatorException {
        UIInput iInput = (UIInput) component;
        if (iInput.isValid()) {
            Double number = (Double) obj;
            if (number < 0) {
                FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_WARN, "Number is invalid", "Number is invalid");
                throw new ValidatorException(message);
            }
        }
    }

    private boolean validateInput() {
        boolean result = true;
        FacesContext context = FacesContext.getCurrentInstance();
        if (vacancy.getMaximumSalary() < vacancy.getMinimumSalary()) {
            FacesMessage message = new FacesMessage(
                    FacesMessage.SEVERITY_WARN,
                    "Number is greater than minimum salary",
                    "Number is greater than minimum salary");
            context.addMessage("msgMaximumSalary", message);
            result = false;
        } else if (vacancy.getMaximumAge() < vacancy.getMinimumAge()) {
            FacesMessage message = new FacesMessage(
                    FacesMessage.SEVERITY_WARN,
                    "Age is greater than minimum age",
                    "Age is greater than minimum age");
            context.addMessage("msgMaximumAge", message);
            result = false;
        }
        return result;
    }

    public void validateMinAge(FacesContext context, UIComponent component, Object object) throws ValidatorException {
        UIInput uIInput = (UIInput) component;
        if (uIInput.isValid()) {
            int number = (Integer) object;
            if (number < 0) {
                FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_WARN, "Number is invalid", "Number is invalid");
                throw new ValidatorException(message);
            }
        }
    }

    public void validateMaxAge(FacesContext context, UIComponent component, Object object) throws ValidatorException {
        UIInput iInput = (UIInput) component;
        if (iInput.isValid()) {
            int number = (Integer) object;
            if (number < 0) {
                FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_WARN, "Number is invalid", "Number is invalid");
                throw new ValidatorException(message);
            }
        }
    }

    public String getVacancyID() {
        return vacancyID;
    }

    public void setVacancyID(String vacancyID) {
        this.vacancyID = vacancyID;
    }

    public String editVacancy() {
        if (!validateInput()) {
            FacesMessage message = new FacesMessage(
                    FacesMessage.SEVERITY_ERROR,
                    "An error occured",
                    "An error occured");
            FacesContext.getCurrentInstance().addMessage(null, message);
        }

        vacancyService = new VacancyService();
        vacancyService.beginTransaction();
        department = departmentService.getDeparmentById(id);
        vacancyService.editVacancy(vacancy.getVacancyID(), vacancy.getTitle(), department,
                vacancy.getNumberRequirement(), vacancy.getStatus(), vacancy.getPosition(),
                vacancy.getWorkingPlace(), vacancy.getWorkType(), vacancy.getMinimumSalary(),
                vacancy.getMaximumSalary(), vacancy.getDescription(), vacancy.getSkillRequirement(),
                vacancy.getEntitlement(), vacancy.getMinimumAge(), vacancy.getMaximumAge(),
                vacancy.getGender(), vacancy.getDegree(), vacancy.getYearOfExperience(),

recruitment-process-system-2012/Source Code/RecruitmentProcessSystem/web/dashboard.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    template="./templates/rpsTemplate.xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core">

    <ui:define name="content">
        <p:growl id="growl" showDetail="true" globalOnly="true"/>
        <h:form id="frm-statistic">            
            <div class="content-box">
                <div class="content-box-header">
                    <h3>Statistics about vacancy</h3>
                </div><!-- End .content-box-header -->

                <div class="content-box-content">
                    <div class="tab-content default-tab">
                        <p:barChart id="basic" value="#{statisticBean.vacancyModel}" legendPosition="ne"
                                    title="Top 5 Favorite Vacancies"
                                    xaxisLabel="Vacancy"
                                    yaxisLabel="Number of registered applicants"
                                    style="height:300px"
                                    styleClass="chart"/>
                    </div>
                </div>
            </div>
            <div class="clear"/>
            <div class="content-box">
                <div class="content-box-header">
                    <h3>Statistics about applicant</h3>
                </div><!-- End .content-box-header -->

                <div class="content-box-content">
                    <div class="tab-content default-tab">
                        <p:lineChart id="line" value="#{statisticBean.applicantModel}"
                                     legendPosition="ne"
                                     title="Number of registered applicants in
                                     #{calendarMB.yearFormat(calendarMB.currentDate)}"
                                     xaxisLabel="Month"
                                     yaxisLabel="Number of registered applicants"
                                     style="height:300px"
                                     styleClass="chart"/>
                    </div>
                </div>
            </div>
        </h:form>
    </ui:define>

</ui:composition>

recruitment-process-system-2012/Source Code/RecruitmentProcessSystem/web/vacancy.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    template="./templates/rpsTemplate.xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core">

    <ui:define name="content">
        <p:growl id="growl" showDetail="true" globalOnly="true"/>
        <h:form id="frm-vacancy">
            <div class="content-box column-left">
                <div class="content-box-header">
                    <h3>Vacancy Information</h3>
                </div><!-- End .content-box-header -->

                <div class="content-box-content">
                    <div class="tab-content default-tab">
                        <fieldset>
                            <p>
                                <label>Title</label>
                                <h:inputText value="#{vacancyMB.vacancy.title}"
                                             required="true"
                                             requiredMessage="You must enter title"
                                             id="title"
                                             styleClass="text-input medium-input"/>
                                <h:message for="title"
                                           infoClass="input-notification success png_bg"
                                           warnClass="input-notification attention png_bg"
                                           errorClass="input-notification error png_bg"/>
                            </p>
                            <p>
                                <label>Department</label>
                                <h:selectOneMenu value="#{vacancyMB.id}"
                                                 styleClass="medium-input">
                                    <f:selectItems value="#{vacancyMB.departments}"
                                                   var="dp"
                                                   itemLabel="#{dp.name}"
                                                   itemValue="#{dp.departmentID}"/>
                                </h:selectOneMenu>
                            </p>
                            <p>
                                <label>Number Requirement</label>
                                <h:inputText value="#{vacancyMB.vacancy.numberRequirement}"
                                             id="numberRequirement" required="true"
                                             requiredMessage="You must enter number"
                                             converterMessage="Number Requirement is wrong format"
                                             validator="#{vacancyMB.validateNumberRequirement}"
                                             styleClass="text-input small-input"/>
                                <h:message for="numberRequirement"
                                           infoClass="input-notification success png_bg"
                                           warnClass="input-notification attention png_bg"
                                           errorClass="input-notification error png_bg"/>
                            </p>
                            <p>
                                <label>Position</label>
                                <h:inputText value="#{vacancyMB.vacancy.position}"
                                             required="true" id="position"
                                             requiredMessage="You must enter position"
                                             styleClass="text-input medium-input"/>
                                <h:message for="position"
                                           infoClass="input-notification success png_bg"
                                           warnClass="input-notification attention png_bg"
                                           errorClass="input-notification error png_bg"/>
                            </p>
                            <p>
                                <label>Working place</label>
                                <h:inputText value="#{vacancyMB.vacancy.workingPlace}"
                                             id="workingplace"
                                             styleClass="text-input medium-input"/>
                            </p>
                            <p>
                                <label>Work type</label>
                                <h:selectOneMenu value="#{vacancyMB.vacancy.workType}"
                                                 styleClass="text-input small-input">
                                    <f:selectItem itemValue="Part time" itemLabel="Part Time"/>
                                    <f:selectItem itemValue="Full time" itemLabel="Full Time"/>
                                </h:selectOneMenu>
                            </p>
                            <p>
                                <label>Entitlement</label>
                                <h:inputTextarea value="#{vacancyMB.vacancy.entitlement}"
                                                 styleClass="text-input textarea medium-input"
                                                 cols="80" rows="5" id="txtEntitlement"/>
                            </p>
                            <p>
                                <label>Probationary Period</label>
                                <h:inputTextarea value="#{vacancyMB.vacancy.probationaryPeriod}"
                                                 styleClass="text-input textarea medium-input"
                                                 cols="80" rows="5" id="txtPeriod"/>
                            </p>
                            <p>
                                <label>Description</label>
                                <h:inputTextarea value="#{vacancyMB.vacancy.description}"
                                                 styleClass="text-input textarea medium-input"
                                                 cols="80" rows="5" id="txtDescription"/>
                            </p>
                            <p>
                                <label>Deadline</label>
                                <p:calendar value="#{vacancyMB.vacancy.deadline}"
                                            styleClass="remove"/>
                            </p>
                        </fieldset>
                    </div>
                </div>
            </div>
            <div class="content-box column-right">
                <div class="content-box-header">
                    <h3>Requirement Information</h3>
                </div><!-- End .content-box-header -->

                <div class="content-box-content">
                    <div class="tab-content default-tab">
                        <fieldset>
                            <p>
                                <label> Minimum Salary</label>
                                <h:inputText id="MininumSalary"
                                             value="#{vacancyMB.vacancy.minimumSalary}"
                                             validator="#{vacancyMB.validateMinSalary}"
                                             converterMessage="You must enter number"
                                             styleClass="text-input small-input">

                                </h:inputText>
                                <h:message for="MininumSalary"
                                           infoClass="input-notification success png_bg"
                                           warnClass="input-notification attention png_bg"
                                           errorClass="input-notification error png_bg"/>

                            </p>
                            <p>
                                <label>Maximum Salary</label>
                                <h:inputText id="MaximumSalary"
                                             value="#{vacancyMB.vacancy.maximumSalary}"
                                             validator="#{vacancyMB.validateMaxSalary}"
                                             converterMessage="You must enter number"
                                             styleClass="text-input small-input"/>
                                <h:message for="MaximumSalary"
                                           id="msgMaximumSalary"
                                           infoClass="input-notification success png_bg"
                                           warnClass="input-notification attention png_bg"
                                           errorClass="input-notification error png_bg"/>
                            </p>
                            <p>
                                <label>Skill Requirement</label>
                                <h:inputTextarea value="#{vacancyMB.vacancy.skillRequirement}"
                                                 styleClass="text-input textarea medium-input"
                                                 cols="80" rows="5" id="txtSkill"/>
                            </p>
                            <p>
                                <label>Minimum Age</label>
                                <h:inputText value="#{vacancyMB.vacancy.minimumAge}"
                                             styleClass="text-input small-input"
                                             id="minAge" validator="#{vacancyMB.validateMinAge}"
                                             converterMessage="Your must enter number"/>
                                <h:message for="minAge" infoClass="input-notification success png_bg"
                                           warnClass="input-notification attention png_bg"
                                           errorClass="input-notification error png_bg"/>
                            </p>
                            <p>
                                <label>Maximum Age</label>
                                <h:inputText value="#{vacancyMB.vacancy.maximumAge}"
                                             styleClass="text-input small-input"
                                             id="maxAge" validator="#{vacancyMB.validateMaxAge}"
                                             converterMessage="Your must enter number"/>
                                <h:message for="maxAge"
                                           id="msgMaximumAge"
                                           infoClass="input-notification success png_bg"
                                           warnClass="input-notification attention png_bg"
                                           errorClass="input-notification error png_bg"/>
                            </p>
                            <p>
                                <label>Gender</label>
                                <h:selectOneMenu value="#{vacancyMB.vacancy.gender}"
                                                 styleClass="text-input small-input">
                                    <f:selectItem itemValue="True" itemLabel="Male"/>
                                    <f:selectItem itemValue="False" itemLabel="Female"/>
                                </h:selectOneMenu>
                            </p>
                            <p>
                                <label>Degree</label>
                                <h:inputTextarea value="#{vacancyMB.vacancy.degree}"
                                                 styleClass="text-input textarea medium-input"
                                                 cols="80" rows="5" id="txtDegree"/>
                            </p>
                            <p>
                                <label>Year Of Experience</label>
                                <h:inputText value="#{vacancyMB.vacancy.yearOfExperience}"
                                             id="yearOfExperience" converterMessage="Number requirement is wrong format"
                                             validator="#{vacancyMB.validateYearOfExperience}"
                                             styleClass="text-input small-input"/>
                                <h:message for="yearOfExperience"
                                           infoClass="input-notification success png_bg"
                                           warnClass="input-notification attention png_bg"
                                           errorClass="input-notification error png_bg"/>
                            </p>
                        </fieldset>
                    </div>
                </div>
            </div>
            <p style="margin-left: 52%;">
                <h:panelGroup rendered="#{empty vacancyMB.vacancy.vacancyID}">
                    <h:commandButton id="btnNew"
                                     styleClass="button"
                                     value="Create new"
                                     action="#{vacancyMB.insertVacancy}"/>

                </h:panelGroup>
                <h:panelGroup rendered="#{not empty vacancyMB.vacancy.vacancyID}">
                    <h:commandButton id="btnSave"
                                     styleClass="button"
                                     value="Save changes"
                                     action="#{vacancyMB.editVacancy}">
                        <f:param name="id" value="#{param.id}"/>
                    </h:commandButton>
                </h:panelGroup>
            </p>
            <div class="clear"/>
        </h:form>
        <script type="text/javascript" >
            $('.remove input').removeClass('ui-inputfield');
        </script>
    </ui:define>

</ui:composition>